### ISSUE TITLE
Eukcc does not work properly after installation

### ISSUE THREAD

**Issue by 389419784** [Finn-Lab/EukCC#24]
Hello,

I try to use eukcc to run my eukaryotic bins, but I can't run normally after installation. How can I solve it?

**Using the recommended installation method, use get eukcc quickly by fetching the container as follows**:
export EUKCC2_DB=/public/home/liqm_1/zhanghx/EukCC/eukcc2_db_ver_1
singularity exec /public/home/liqm_1/zhanghx/EukCC/eukcc2.simg eukcc single --out /public/home/liqm_1/zhanghx/WDNA/eukcc/output --threads 40 /public/home/liqm_1/zhanghx/WDNA/old/new/euk_contigs.fa

**And the error is:** 
21-07-2021 07:58:01:  EukCC version 2.0 RC2
21-07-2021 07:58:01:  Found 3 bins
21-07-2021 07:58:03:  Faa folder exists, remove if you want to rerun this analsys, will reuse it for now
21-07-2021 07:58:03:  Searching for marker genes in base database
21-07-2021 07:58:03:  Found 10 marker genes, placing them in the tree using epa-ng
NCBI database not present yet (first time used?)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/opt/conda/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/bin/eukcc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/eukcc/__main__.py", line 408, in main
    eukcc_folder(args)
  File "/opt/conda/lib/python3.8/site-packages/eukcc/refine.py", line 65, in eukcc_folder
    refine(state)
  File "/opt/conda/lib/python3.8/site-packages/eukcc/refine.py", line 149, in refine
    bins.append(bin(state, wd, path, protein=True))
  File "/opt/conda/lib/python3.8/site-packages/eukcc/bin.py", line 23, in __init__
    self.run_eukcc()
  File "/opt/conda/lib/python3.8/site-packages/eukcc/bin.py", line 43, in run_eukcc
    clade = E.determine_subdb()
  File "/opt/conda/lib/python3.8/site-packages/eukcc/eukcc.py", line 359, in determine_subdb
    lng = tax_LCA(tree, info, places)
  File "/opt/conda/lib/python3.8/site-packages/eukcc/treehandler.py", line 138, in tax_LCA
info = load_tax_info(taxinfo)
  File "/opt/conda/lib/python3.8/site-packages/eukcc/base.py", line 55, in load_tax_info
    ncbi = NCBITaxa()
  File "/opt/conda/lib/python3.8/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 112, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/opt/conda/lib/python3.8/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 131, in update_taxonomy_database
    update_db(self.dbfile)
  File "/opt/conda/lib/python3.8/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 758, in update_db
    (md5_filename, _) = urlretrieve("https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5")
  File "/opt/conda/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

**While I use conda to install,  the following error will be reported, and I have installed guppy3 in Python3

eukcc folder     --out /public/home/liqm_1/zhanghx/WDNA/INITIAL_BINNING/eukcc     --threads 80      --links /public/home/liqm_1/zhanghx/WDNA/INITIAL_BINNING/concoct_linktable.csv      /public/home/liqm_1/zhanghx/WDNA/INITIAL_BINNING/concoct_bins
26-07-2021 09:57:49:  EukCC version 2.0
26-07-2021 09:57:49:  Found 4 bins
26-07-2021 09:57:50:  Missing dependencies.
Traceback (most recent call last):
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/bin/eukcc", line 10, in <module>
    sys.exit(main())
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/lib/python3.9/site-packages/eukcc/__main__.py", line 413, in main
    eukcc_folder(args)
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/lib/python3.9/site-packages/eukcc/refine.py", line 65, in eukcc_folder
    refine(state)
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/lib/python3.9/site-packages/eukcc/refine.py", line 133, in refine
    E = eukcc(state)
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/lib/python3.9/site-packages/eukcc/eukcc.py", line 184, in __init__
    self.check_dependencies()
  File "/public/home/liqm_1/software/miniconda3/envs/eukcc/lib/python3.9/site-packages/eukcc/eukcc.py", line 795, in check_dependencies
    raise EnvironmentError("Missing dependencies: {}".format(", ".join(missing)))
OSError: Missing dependencies: guppy

**Comment by openpaul** [comment]
`NCBI database not present yet (first time used?)`

it seems your ete3 installation has not been used before. Please run 

```
eukcc ncbi_update
```
Or run python and setup ete3 as mentioned here: http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html

And try again.

For the conda install, you will need to install pplacer (https://anaconda.org/bioconda/pplacer) using conda as guppy is installed this way. 

I hope that helps you get eukcc started.

**Comment by 389419784** [comment]
> `NCBI database not present yet (first time used?)`
> 
> it seems your ete3 installation has not been used before. Please run
> 
> ```
> eukcc ncbi_update
> ```
> 
> Or run python and setup ete3 as mentioned here: http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html
> 
> And try again.
> 
> For the conda install, you will need to install pplacer (https://anaconda.org/bioconda/pplacer) using conda as guppy is installed this way.
> 
> I hope that helps you get eukcc started.

For the first installation method, run "eukcc ncbi_update" does not seem to work. For the conda install, your suggestions are useful. Thank you very much for your reply.

**Comment by openpaul** [comment]
Glad I could help. Will close the issue for now
