### ISSUE TITLE
FileNotFoundError: Could not find fasta file

### ISSUE THREAD

**Issue by alienn233** [Finn-Lab/EukCC#35]
coomand :
 docker run -it  quay.io/microbiome-informatics/eukcc   single --out outfolder  --threads 8 --db ~/software/eukccdb/eukcc2_db_ver_1.1 ~/software/eukccdb/EukCC-master/tests/testfiles/N50_1.fa

err::
Traceback (most recent call last):
  File "/opt/conda/bin/eukcc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/eukcc/__main__.py", line 495, in main
    run_eukcc(args)
  File "/opt/conda/lib/python3.8/site-packages/eukcc/__main__.py", line 57, in run_eukcc
    state["seqtype"] = determine_type(state["fasta"])
  File "/opt/conda/lib/python3.8/site-packages/eukcc/fasta.py", line 27, in determine_type
    for record in fa:
  File "/opt/conda/lib/python3.8/site-packages/eukcc/fasta.py", line 93, in Fasta
    if validate_fasta(path) is False:
  File "/opt/conda/lib/python3.8/site-packages/eukcc/fasta.py", line 135, in validate_fasta
    raise FileNotFoundError("Could not find fasta file")
FileNotFoundError: Could not find fasta file

But  i already had fasta file

**Comment by openpaul** [comment]
Your homefolder might not be mounted in the docker container? 
The fasta file is not reachable for eukcc.
This should not be a bug in EukCC but likely is just some permission/docker issue
