### ISSUE TITLE
binlinks.py , IndexError: list index out of range

### ISSUE THREAD

**Issue by haihao999** [Finn-Lab/EukCC#37]
Hi,
I don't know why there is a failure, the steps are the same, Could you help me?

Number of  Commands: 3
13-02-2023 10:46:45:  Parsing Bam file. This can take a few moments
13-02-2023 10:46:46:  Parsing Bam file. This can take a few moments
13-02-2023 10:46:50:  Parsing Bam file. This can take a few moments
13-02-2023 10:46:53:  Writing output
Traceback (most recent call last):
  File "/home/shang/anaconda3/envs/eukcc/bin/binlinks.py", line 209, in <module>
    main()
  File "/home/shang/anaconda3/envs/eukcc/bin/binlinks.py", line 202, in main
    cout = csv.DictWriter(fout, fieldnames=list(out_data[0].keys()))
IndexError: list index out of range
13-02-2023 11:09:29:  Writing output
13-02-2023 11:10:12:  Writing output

**Comment by javiercnav** [comment]
Hello there, I want to follow-up on this issue.
I am getting the same error when trying binlinks.py
Any thoughts?
