### ISSUE TITLE
Error taxid not found

### ISSUE THREAD

**Issue by sarah872** [Finn-Lab/EukCC#9]
Hi,
I'm running `EukCC version 0.2` on the test genome.
```
eukcc --db eukcc_db_20191023_1_v1.1/ --ncores 10 --ncorespplacer 10 --outdir eukcc_testgenome testgenome.fa
```
and I am getting the following error:
```
09/15/2020 13:51:12:  Starting EukCC
09/15/2020 13:51:21:  MAG succesfully placed in tree
09/15/2020 13:51:21:  Using pressed hmms from last run
09/15/2020 13:51:21:  45354 taxid not found
09/15/2020 13:51:21:  284592 taxid not found
09/15/2020 13:51:21:  984486 taxid not found
09/15/2020 13:51:21:  379508 taxid not found
09/15/2020 13:51:21:  1789683 taxid not found
09/15/2020 13:51:21:  28985 taxid not found
09/15/2020 13:51:21:  1230905 taxid not found
09/15/2020 13:51:21:  39416 taxid not found
09/15/2020 13:51:21:  857566 taxid not found
09/15/2020 13:51:21:  294747 taxid not found
09/15/2020 13:51:21:  5486 taxid not found
09/15/2020 13:51:21:  1382522 taxid not found
09/15/2020 13:51:21:  36022 taxid not found
09/15/2020 13:51:21:  669874 taxid not found
09/15/2020 13:51:21:  619300 taxid not found
09/15/2020 13:51:21:  45357 taxid not found
09/15/2020 13:51:21:  1333698 taxid not found
09/15/2020 13:51:21:  5480 taxid not found
09/15/2020 13:51:21:  1344418 taxid not found
09/15/2020 13:51:21:  4956 taxid not found
09/15/2020 13:51:21:  1266660 taxid not found
09/15/2020 13:51:21:  983967 taxid not found
09/15/2020 13:51:21:  237561 taxid not found
09/15/2020 13:51:21:  559292 taxid not found
09/15/2020 13:51:21:  418784 taxid not found
09/15/2020 13:51:21:  56408 taxid not found
09/15/2020 13:51:21:  871575 taxid not found
09/15/2020 13:51:21:  306902 taxid not found
09/15/2020 13:51:21:  644223 taxid not found
09/15/2020 13:51:21:  931890 taxid not found
09/15/2020 13:51:21:  1071378 taxid not found
09/15/2020 13:51:21:  436907 taxid not found
09/15/2020 13:51:21:  984487 taxid not found
09/15/2020 13:51:21:  1071380 taxid not found
09/15/2020 13:51:21:  284591 taxid not found
09/15/2020 13:51:21:  4955 taxid not found
09/15/2020 13:51:21:  869754 taxid not found
09/15/2020 13:51:21:  698492 taxid not found
09/15/2020 13:51:21:  1003335 taxid not found
09/15/2020 13:51:21:  590646 taxid not found
09/15/2020 13:51:21:  1071381 taxid not found
09/15/2020 13:51:21:  1245769 taxid not found
09/15/2020 13:51:21:  1266666 taxid not found
09/15/2020 13:51:21:  1071383 taxid not found
09/15/2020 13:51:21:  559295 taxid not found
09/15/2020 13:51:21:  1173061 taxid not found
09/15/2020 13:51:21:  984485 taxid not found
09/15/2020 13:51:21:  1245528 taxid not found
09/15/2020 13:51:21:  4950 taxid not found
09/15/2020 13:51:21:  5478 taxid not found
09/15/2020 13:51:21:  1064592 taxid not found
09/15/2020 13:51:21:  284811 taxid not found
09/15/2020 13:51:21:  1073089 taxid not found
09/15/2020 13:51:21:  683960 taxid not found
09/15/2020 13:51:21:  498019 taxid not found
09/15/2020 13:51:21:  1071382 taxid not found
09/15/2020 13:51:21:  983966 taxid not found
09/15/2020 13:51:21:  322104 taxid not found
09/15/2020 13:51:21:  1041607 taxid not found
09/15/2020 13:51:21:  45286 taxid not found
09/15/2020 13:51:21:  226230 taxid not found
09/15/2020 13:51:21:  294746 taxid not found
Traceback (most recent call last):
  File "/home/user/py3-venv/bin/eukcc", line 8, in <module>
    sys.exit(main())
  File "/home/user/py3-venv/lib/python3.7/site-packages/eukcc/__main__.py", line 222, in main
    _ = m.inferLineage(m.placements[m.cfg["placementMethod"]])
  File "/home/user/py3-venv/lib/python3.7/site-packages/eukcc/workflow.py", line 306, in inferLineage
    common = set(lngs[0])
IndexError: list index out of range
```

**Comment by openpaul** [comment]
Hello,
thanks for reporting this. You will need to update the ete3 cache its seems to me. Could you update it following the instructions given here and test again?

http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html#upgrading-the-local-database

**Comment by sarah872** [comment]
Thank you! No more errors.
